name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test Print
        env:
          GREETING: Hi there!
        run: |
          echo $GREETING

